#!/bin/sh

read -r cache <"${0%/*}/cache_location"
if [ -z "$cache" ]; then
	exit 0
fi

TS=ts
if ! command -v "$TS" >/dev/null; then
	TS=tsp
fi

export PATH="/nix/var/nix/profiles/default/bin:$PATH"
xargs -t "$TS" nix copy --to "file://$cache" <<-EOF >/dev/null
	$OUT_PATHS
EOF
