on: push
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - run: nix registry add nixpkgs github:nixos/nixpkgs/nixos-22.11
      - run: nix -L build
      - name: Sanity Check
        run: |
          ./result/bin/okta-aws-cli --help 2>&1 \
            | grep -wF -- '--all-profiles'
