on: push
jobs:
  build:
    environment: build
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: nix-cache
        with:
          path: ${{ runner.temp }}/nix-cache
          key: ${{ runner.os }}-${{ hashFiles('./flake.lock', './gomod2nix.toml') }}-3

      - name: Save signing key secret to file
        run: printf '${{ secrets.NIX_PRIVATE_KEY }}\n' >'${{ runner.temp }}/nix-private-key'

      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            extra-substituters = file://${{ runner.temp }}/nix-cache
            secret-key-files = ${{ runner.temp }}/nix-private-key
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= ${{ vars.NIX_PUBLIC_KEY }}

      - name: Enable post-build-hook
        if: steps.nix-cache.outputs.cache-hit != 'true'
        run: |
          printf '${{ runner.temp }}/nix-cache\n' >'${{ github.workspace}}/.github/cache_location'
          printf 'post-build-hook = ${{ github.workspace }}/.github/nix-post-build-hook' \
            | sudo tee -a /etc/nix/nix.conf >/dev/null

          case '${{ runner.os }}' in
          Linux)
            sudo apt update && sudo apt install -y task-spooler
            sudo systemctl restart nix-daemon
            ;;
          macOS)
            brew update && brew install task-spooler
            sudo launchctl kickstart -k system/org.nixos.nix-daemon
            ;;
          *)
            printf 'unknown OS: %s\n' '${{ runner.os }}' >&2
            exit 1
          esac

      - run: nix -L build

      - name: Sanity Check
        run: |
          ./result/bin/okta-aws-cli --help 2>&1 \
            | grep -wF -- '--all-profiles'

      - name: Copy Nix dependencies to cache
        if: steps.nix-cache.outputs.cache-hit != 'true'
        run: |
          ts -l | {
            read -r rest
            while read -r id rest; do
              ts -c "$id"
            done
          }
